// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvgfinovmbswqsgwxtit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Z2Zpbm92bWJzd3FzZ3d4dGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzUzOTEsImV4cCI6MjA2NTIxMTM5MX0.-seuVxx28yxcwDBbhPO2kyVOAQA_G8AsAE347bNgGFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);